/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DropshipRouteImport } from './routes/dropship'
import { Route as DropshipIndexRouteImport } from './routes/dropship/index'
import { Route as DropshipDashboardRouteImport } from './routes/dropship/dashboard'
import { Route as DropshipDocRouteImport } from './routes/dropship/doc'
import { Route as DropshipProgressRouteImport } from './routes/dropship/progress'
import { Route as DropshipDocIndexRouteImport } from './routes/dropship/doc/index'
import { Route as DropshipDocAiAgentRouteImport } from './routes/dropship/doc/ai-agent'
import { Route as DropshipDocLabRouteImport } from './routes/dropship/doc/lab'
import { Route as DropshipDocResearchRouteImport } from './routes/dropship/doc/research'
import { Route as DropshipProgressIndexRouteImport } from './routes/dropship/progress/index'
import { Route as DropshipProgress0TimelineRouteImport } from './routes/dropship/progress/0-timeline'
import { Route as DropshipProgress1MarketResearchRouteImport } from './routes/dropship/progress/1-market-research'
import { Route as DropshipProgress2StoreRouteImport } from './routes/dropship/progress/2-store'
import { Route as DropshipProgress3VideoCreativeRouteImport } from './routes/dropship/progress/3-video-creative'
import { Route as DropshipDocQuyTrinh2026IndexRouteImport } from './routes/dropship/doc/quy-trinh-2026/index'
import { Route as DropshipDocQuyTrinh2026StepSlugRouteImport } from './routes/dropship/doc/quy-trinh-2026/$stepSlug'
import { Route as DropshipDocReadingIndexRouteImport } from './routes/dropship/doc/reading/index'
import { Route as DropshipDocReadingSlugRouteImport } from './routes/dropship/doc/reading/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DropshipRoute = DropshipRouteImport.update({
  id: '/dropship',
  path: '/dropship',
  getParentRoute: () => rootRouteImport,
} as any)
const DropshipIndexRoute = DropshipIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DropshipRoute,
} as any)
const DropshipDashboardRoute = DropshipDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => DropshipRoute,
} as any)
const DropshipDocRoute = DropshipDocRouteImport.update({
  id: '/doc',
  path: '/doc',
  getParentRoute: () => DropshipRoute,
} as any)
const DropshipProgressRoute = DropshipProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => DropshipRoute,
} as any)
const DropshipDocIndexRoute = DropshipDocIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DropshipDocRoute,
} as any)
const DropshipDocAiAgentRoute = DropshipDocAiAgentRouteImport.update({
  id: '/ai-agent',
  path: '/ai-agent',
  getParentRoute: () => DropshipDocRoute,
} as any)
const DropshipDocLabRoute = DropshipDocLabRouteImport.update({
  id: '/lab',
  path: '/lab',
  getParentRoute: () => DropshipDocRoute,
} as any)
const DropshipDocResearchRoute = DropshipDocResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => DropshipDocRoute,
} as any)
const DropshipProgressIndexRoute = DropshipProgressIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DropshipProgressRoute,
} as any)
const DropshipProgress0TimelineRoute =
  DropshipProgress0TimelineRouteImport.update({
    id: '/0-timeline',
    path: '/0-timeline',
    getParentRoute: () => DropshipProgressRoute,
  } as any)
const DropshipProgress1MarketResearchRoute =
  DropshipProgress1MarketResearchRouteImport.update({
    id: '/1-market-research',
    path: '/1-market-research',
    getParentRoute: () => DropshipProgressRoute,
  } as any)
const DropshipProgress2StoreRoute = DropshipProgress2StoreRouteImport.update({
  id: '/2-store',
  path: '/2-store',
  getParentRoute: () => DropshipProgressRoute,
} as any)
const DropshipProgress3VideoCreativeRoute =
  DropshipProgress3VideoCreativeRouteImport.update({
    id: '/3-video-creative',
    path: '/3-video-creative',
    getParentRoute: () => DropshipProgressRoute,
  } as any)
const DropshipDocQuyTrinh2026IndexRoute =
  DropshipDocQuyTrinh2026IndexRouteImport.update({
    id: '/quy-trinh-2026/',
    path: '/quy-trinh-2026/',
    getParentRoute: () => DropshipDocRoute,
  } as any)
const DropshipDocQuyTrinh2026StepSlugRoute =
  DropshipDocQuyTrinh2026StepSlugRouteImport.update({
    id: '/quy-trinh-2026/$stepSlug',
    path: '/quy-trinh-2026/$stepSlug',
    getParentRoute: () => DropshipDocRoute,
  } as any)
const DropshipDocReadingIndexRoute = DropshipDocReadingIndexRouteImport.update({
  id: '/reading/',
  path: '/reading/',
  getParentRoute: () => DropshipDocRoute,
} as any)
const DropshipDocReadingSlugRoute = DropshipDocReadingSlugRouteImport.update({
  id: '/reading/$slug',
  path: '/reading/$slug',
  getParentRoute: () => DropshipDocRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dropship': typeof DropshipRouteWithChildren
  '/dropship/dashboard': typeof DropshipDashboardRoute
  '/dropship/doc': typeof DropshipDocRouteWithChildren
  '/dropship/progress': typeof DropshipProgressRouteWithChildren
  '/dropship/': typeof DropshipIndexRoute
  '/dropship/doc/ai-agent': typeof DropshipDocAiAgentRoute
  '/dropship/doc/lab': typeof DropshipDocLabRoute
  '/dropship/doc/research': typeof DropshipDocResearchRoute
  '/dropship/progress/0-timeline': typeof DropshipProgress0TimelineRoute
  '/dropship/progress/1-market-research': typeof DropshipProgress1MarketResearchRoute
  '/dropship/progress/2-store': typeof DropshipProgress2StoreRoute
  '/dropship/progress/3-video-creative': typeof DropshipProgress3VideoCreativeRoute
  '/dropship/doc/': typeof DropshipDocIndexRoute
  '/dropship/progress/': typeof DropshipProgressIndexRoute
  '/dropship/doc/quy-trinh-2026/$stepSlug': typeof DropshipDocQuyTrinh2026StepSlugRoute
  '/dropship/doc/reading/$slug': typeof DropshipDocReadingSlugRoute
  '/dropship/doc/quy-trinh-2026/': typeof DropshipDocQuyTrinh2026IndexRoute
  '/dropship/doc/reading/': typeof DropshipDocReadingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dropship/dashboard': typeof DropshipDashboardRoute
  '/dropship': typeof DropshipIndexRoute
  '/dropship/doc/ai-agent': typeof DropshipDocAiAgentRoute
  '/dropship/doc/lab': typeof DropshipDocLabRoute
  '/dropship/doc/research': typeof DropshipDocResearchRoute
  '/dropship/progress/0-timeline': typeof DropshipProgress0TimelineRoute
  '/dropship/progress/1-market-research': typeof DropshipProgress1MarketResearchRoute
  '/dropship/progress/2-store': typeof DropshipProgress2StoreRoute
  '/dropship/progress/3-video-creative': typeof DropshipProgress3VideoCreativeRoute
  '/dropship/doc': typeof DropshipDocIndexRoute
  '/dropship/progress': typeof DropshipProgressIndexRoute
  '/dropship/doc/quy-trinh-2026/$stepSlug': typeof DropshipDocQuyTrinh2026StepSlugRoute
  '/dropship/doc/reading/$slug': typeof DropshipDocReadingSlugRoute
  '/dropship/doc/quy-trinh-2026': typeof DropshipDocQuyTrinh2026IndexRoute
  '/dropship/doc/reading': typeof DropshipDocReadingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dropship': typeof DropshipRouteWithChildren
  '/dropship/dashboard': typeof DropshipDashboardRoute
  '/dropship/doc': typeof DropshipDocRouteWithChildren
  '/dropship/progress': typeof DropshipProgressRouteWithChildren
  '/dropship/': typeof DropshipIndexRoute
  '/dropship/doc/ai-agent': typeof DropshipDocAiAgentRoute
  '/dropship/doc/lab': typeof DropshipDocLabRoute
  '/dropship/doc/research': typeof DropshipDocResearchRoute
  '/dropship/progress/0-timeline': typeof DropshipProgress0TimelineRoute
  '/dropship/progress/1-market-research': typeof DropshipProgress1MarketResearchRoute
  '/dropship/progress/2-store': typeof DropshipProgress2StoreRoute
  '/dropship/progress/3-video-creative': typeof DropshipProgress3VideoCreativeRoute
  '/dropship/doc/': typeof DropshipDocIndexRoute
  '/dropship/progress/': typeof DropshipProgressIndexRoute
  '/dropship/doc/quy-trinh-2026/$stepSlug': typeof DropshipDocQuyTrinh2026StepSlugRoute
  '/dropship/doc/reading/$slug': typeof DropshipDocReadingSlugRoute
  '/dropship/doc/quy-trinh-2026/': typeof DropshipDocQuyTrinh2026IndexRoute
  '/dropship/doc/reading/': typeof DropshipDocReadingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dropship'
    | '/dropship/dashboard'
    | '/dropship/doc'
    | '/dropship/progress'
    | '/dropship/'
    | '/dropship/doc/ai-agent'
    | '/dropship/doc/lab'
    | '/dropship/doc/research'
    | '/dropship/progress/0-timeline'
    | '/dropship/progress/1-market-research'
    | '/dropship/progress/2-store'
    | '/dropship/progress/3-video-creative'
    | '/dropship/doc/'
    | '/dropship/progress/'
    | '/dropship/doc/quy-trinh-2026/$stepSlug'
    | '/dropship/doc/reading/$slug'
    | '/dropship/doc/quy-trinh-2026/'
    | '/dropship/doc/reading/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dropship/dashboard'
    | '/dropship'
    | '/dropship/doc/ai-agent'
    | '/dropship/doc/lab'
    | '/dropship/doc/research'
    | '/dropship/progress/0-timeline'
    | '/dropship/progress/1-market-research'
    | '/dropship/progress/2-store'
    | '/dropship/progress/3-video-creative'
    | '/dropship/doc'
    | '/dropship/progress'
    | '/dropship/doc/quy-trinh-2026/$stepSlug'
    | '/dropship/doc/reading/$slug'
    | '/dropship/doc/quy-trinh-2026'
    | '/dropship/doc/reading'
  id:
    | '__root__'
    | '/'
    | '/dropship'
    | '/dropship/dashboard'
    | '/dropship/doc'
    | '/dropship/progress'
    | '/dropship/'
    | '/dropship/doc/ai-agent'
    | '/dropship/doc/lab'
    | '/dropship/doc/research'
    | '/dropship/progress/0-timeline'
    | '/dropship/progress/1-market-research'
    | '/dropship/progress/2-store'
    | '/dropship/progress/3-video-creative'
    | '/dropship/doc/'
    | '/dropship/progress/'
    | '/dropship/doc/quy-trinh-2026/$stepSlug'
    | '/dropship/doc/reading/$slug'
    | '/dropship/doc/quy-trinh-2026/'
    | '/dropship/doc/reading/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DropshipRoute: typeof DropshipRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dropship': {
      id: '/dropship'
      path: '/dropship'
      fullPath: '/dropship'
      preLoaderRoute: typeof DropshipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dropship/': {
      id: '/dropship/'
      path: '/'
      fullPath: '/dropship/'
      preLoaderRoute: typeof DropshipIndexRouteImport
      parentRoute: typeof DropshipRoute
    }
    '/dropship/dashboard': {
      id: '/dropship/dashboard'
      path: '/dashboard'
      fullPath: '/dropship/dashboard'
      preLoaderRoute: typeof DropshipDashboardRouteImport
      parentRoute: typeof DropshipRoute
    }
    '/dropship/doc': {
      id: '/dropship/doc'
      path: '/doc'
      fullPath: '/dropship/doc'
      preLoaderRoute: typeof DropshipDocRouteImport
      parentRoute: typeof DropshipRoute
    }
    '/dropship/progress': {
      id: '/dropship/progress'
      path: '/progress'
      fullPath: '/dropship/progress'
      preLoaderRoute: typeof DropshipProgressRouteImport
      parentRoute: typeof DropshipRoute
    }
    '/dropship/doc/': {
      id: '/dropship/doc/'
      path: '/'
      fullPath: '/dropship/doc/'
      preLoaderRoute: typeof DropshipDocIndexRouteImport
      parentRoute: typeof DropshipDocRoute
    }
    '/dropship/doc/ai-agent': {
      id: '/dropship/doc/ai-agent'
      path: '/ai-agent'
      fullPath: '/dropship/doc/ai-agent'
      preLoaderRoute: typeof DropshipDocAiAgentRouteImport
      parentRoute: typeof DropshipDocRoute
    }
    '/dropship/doc/lab': {
      id: '/dropship/doc/lab'
      path: '/lab'
      fullPath: '/dropship/doc/lab'
      preLoaderRoute: typeof DropshipDocLabRouteImport
      parentRoute: typeof DropshipDocRoute
    }
    '/dropship/doc/research': {
      id: '/dropship/doc/research'
      path: '/research'
      fullPath: '/dropship/doc/research'
      preLoaderRoute: typeof DropshipDocResearchRouteImport
      parentRoute: typeof DropshipDocRoute
    }
    '/dropship/progress/': {
      id: '/dropship/progress/'
      path: '/'
      fullPath: '/dropship/progress/'
      preLoaderRoute: typeof DropshipProgressIndexRouteImport
      parentRoute: typeof DropshipProgressRoute
    }
    '/dropship/progress/0-timeline': {
      id: '/dropship/progress/0-timeline'
      path: '/0-timeline'
      fullPath: '/dropship/progress/0-timeline'
      preLoaderRoute: typeof DropshipProgress0TimelineRouteImport
      parentRoute: typeof DropshipProgressRoute
    }
    '/dropship/progress/1-market-research': {
      id: '/dropship/progress/1-market-research'
      path: '/1-market-research'
      fullPath: '/dropship/progress/1-market-research'
      preLoaderRoute: typeof DropshipProgress1MarketResearchRouteImport
      parentRoute: typeof DropshipProgressRoute
    }
    '/dropship/progress/2-store': {
      id: '/dropship/progress/2-store'
      path: '/2-store'
      fullPath: '/dropship/progress/2-store'
      preLoaderRoute: typeof DropshipProgress2StoreRouteImport
      parentRoute: typeof DropshipProgressRoute
    }
    '/dropship/progress/3-video-creative': {
      id: '/dropship/progress/3-video-creative'
      path: '/3-video-creative'
      fullPath: '/dropship/progress/3-video-creative'
      preLoaderRoute: typeof DropshipProgress3VideoCreativeRouteImport
      parentRoute: typeof DropshipProgressRoute
    }
    '/dropship/doc/quy-trinh-2026/': {
      id: '/dropship/doc/quy-trinh-2026/'
      path: '/quy-trinh-2026'
      fullPath: '/dropship/doc/quy-trinh-2026/'
      preLoaderRoute: typeof DropshipDocQuyTrinh2026IndexRouteImport
      parentRoute: typeof DropshipDocRoute
    }
    '/dropship/doc/quy-trinh-2026/$stepSlug': {
      id: '/dropship/doc/quy-trinh-2026/$stepSlug'
      path: '/quy-trinh-2026/$stepSlug'
      fullPath: '/dropship/doc/quy-trinh-2026/$stepSlug'
      preLoaderRoute: typeof DropshipDocQuyTrinh2026StepSlugRouteImport
      parentRoute: typeof DropshipDocRoute
    }
    '/dropship/doc/reading/': {
      id: '/dropship/doc/reading/'
      path: '/reading'
      fullPath: '/dropship/doc/reading/'
      preLoaderRoute: typeof DropshipDocReadingIndexRouteImport
      parentRoute: typeof DropshipDocRoute
    }
    '/dropship/doc/reading/$slug': {
      id: '/dropship/doc/reading/$slug'
      path: '/reading/$slug'
      fullPath: '/dropship/doc/reading/$slug'
      preLoaderRoute: typeof DropshipDocReadingSlugRouteImport
      parentRoute: typeof DropshipDocRoute
    }
  }
}

interface DropshipDocRouteChildren {
  DropshipDocAiAgentRoute: typeof DropshipDocAiAgentRoute
  DropshipDocLabRoute: typeof DropshipDocLabRoute
  DropshipDocResearchRoute: typeof DropshipDocResearchRoute
  DropshipDocIndexRoute: typeof DropshipDocIndexRoute
  DropshipDocQuyTrinh2026StepSlugRoute: typeof DropshipDocQuyTrinh2026StepSlugRoute
  DropshipDocReadingSlugRoute: typeof DropshipDocReadingSlugRoute
  DropshipDocQuyTrinh2026IndexRoute: typeof DropshipDocQuyTrinh2026IndexRoute
  DropshipDocReadingIndexRoute: typeof DropshipDocReadingIndexRoute
}

const DropshipDocRouteChildren: DropshipDocRouteChildren = {
  DropshipDocAiAgentRoute: DropshipDocAiAgentRoute,
  DropshipDocLabRoute: DropshipDocLabRoute,
  DropshipDocResearchRoute: DropshipDocResearchRoute,
  DropshipDocIndexRoute: DropshipDocIndexRoute,
  DropshipDocQuyTrinh2026StepSlugRoute: DropshipDocQuyTrinh2026StepSlugRoute,
  DropshipDocReadingSlugRoute: DropshipDocReadingSlugRoute,
  DropshipDocQuyTrinh2026IndexRoute: DropshipDocQuyTrinh2026IndexRoute,
  DropshipDocReadingIndexRoute: DropshipDocReadingIndexRoute,
}

const DropshipDocRouteWithChildren = DropshipDocRoute._addFileChildren(
  DropshipDocRouteChildren,
)

interface DropshipProgressRouteChildren {
  DropshipProgress0TimelineRoute: typeof DropshipProgress0TimelineRoute
  DropshipProgress1MarketResearchRoute: typeof DropshipProgress1MarketResearchRoute
  DropshipProgress2StoreRoute: typeof DropshipProgress2StoreRoute
  DropshipProgress3VideoCreativeRoute: typeof DropshipProgress3VideoCreativeRoute
  DropshipProgressIndexRoute: typeof DropshipProgressIndexRoute
}

const DropshipProgressRouteChildren: DropshipProgressRouteChildren = {
  DropshipProgress0TimelineRoute: DropshipProgress0TimelineRoute,
  DropshipProgress1MarketResearchRoute: DropshipProgress1MarketResearchRoute,
  DropshipProgress2StoreRoute: DropshipProgress2StoreRoute,
  DropshipProgress3VideoCreativeRoute: DropshipProgress3VideoCreativeRoute,
  DropshipProgressIndexRoute: DropshipProgressIndexRoute,
}

const DropshipProgressRouteWithChildren =
  DropshipProgressRoute._addFileChildren(DropshipProgressRouteChildren)

interface DropshipRouteChildren {
  DropshipDashboardRoute: typeof DropshipDashboardRoute
  DropshipDocRoute: typeof DropshipDocRouteWithChildren
  DropshipProgressRoute: typeof DropshipProgressRouteWithChildren
  DropshipIndexRoute: typeof DropshipIndexRoute
}

const DropshipRouteChildren: DropshipRouteChildren = {
  DropshipDashboardRoute: DropshipDashboardRoute,
  DropshipDocRoute: DropshipDocRouteWithChildren,
  DropshipProgressRoute: DropshipProgressRouteWithChildren,
  DropshipIndexRoute: DropshipIndexRoute,
}

const DropshipRouteWithChildren = DropshipRoute._addFileChildren(
  DropshipRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DropshipRoute: DropshipRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
