/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReadingRouteImport } from './routes/reading'
import { Route as ReadingSlugRouteImport } from './routes/reading/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadingRoute = ReadingRouteImport.update({
  id: '/reading',
  path: '/reading',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadingSlugRoute = ReadingSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ReadingRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/reading': typeof ReadingRouteWithChildren
  '/reading/$slug': typeof ReadingSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/reading': typeof ReadingRouteWithChildren
  '/reading/$slug': typeof ReadingSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/reading': typeof ReadingRouteWithChildren
  '/reading/$slug': typeof ReadingSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/reading' | '/reading/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/reading' | '/reading/$slug'
  id: '__root__' | '/' | '/reading' | '/reading/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ReadingRoute: typeof ReadingRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reading': {
      id: '/reading'
      path: '/reading'
      fullPath: '/reading'
      preLoaderRoute: typeof ReadingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reading/$slug': {
      id: '/reading/$slug'
      path: '/$slug'
      fullPath: '/reading/$slug'
      preLoaderRoute: typeof ReadingSlugRouteImport
      parentRoute: typeof ReadingRoute
    }
  }
}

interface ReadingRouteChildren {
  ReadingSlugRoute: typeof ReadingSlugRoute
}

const ReadingRouteChildren: ReadingRouteChildren = {
  ReadingSlugRoute: ReadingSlugRoute,
}

const ReadingRouteWithChildren =
  ReadingRoute._addFileChildren(ReadingRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ReadingRoute: ReadingRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
